### ISSUE TITLE
Blank Screen Bug

### ISSUE THREAD

**Issue by elliotmandel** [empirical-org/Quill-Grammar#244] opened 2015-11-17 15:42 UTC
Teacher emailed me about issues she was seeing - no activities were loading for her. Screenshots attached. I was unable to replicate.

Teacher email: lailaa_mx3@yahoo.com

![img_5719](https://cloud.githubusercontent.com/assets/12731246/11216165/d156a204-8d17-11e5-9ed1-bd2c1790fb54.jpg)
![img_8259](https://cloud.githubusercontent.com/assets/12731246/11216164/d1563026-8d17-11e5-9afd-eac425cc3f9d.jpg)
![img_9539](https://cloud.githubusercontent.com/assets/12731246/11216163/d155f5a2-8d17-11e5-9d24-bbe5d27131cf.jpg)
![img_9606](https://cloud.githubusercontent.com/assets/12731246/11216167/d15738b8-8d17-11e5-8de4-f8d888db78e9.jpg)
![img_3175](https://cloud.githubusercontent.com/assets/12731246/11216166/d156e21e-8d17-11e5-98eb-0849a93bdf4a.jpg)

**Comment by ddmck** [comment] 2015-11-17 15:54
@elliotmandel This is a duplicate of the previous blank screen bug, that was fixed in most cases by clearing the cache and cookies. Have they already tried doing this?

**Closed** 2015-12-23 22:48 UTC
Labels: bug
